import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/navigation-menu/navigation-menu";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body> 
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <NavBar/> 
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}